### ISSUE TITLE
Logging Config

### ISSUE THREAD

**Issue by Armychais902** [senthilps8/continuous_ssl_problem#2]
Hi Authors,
Thanks for viewing my question! I found that the default logging config isn't provided, could you give a simple explanation of the variables needed and their meanings? I can find several usages in `main.py` but still would like to confirm if my understanding is correct. Thank you!

**Comment by senthilps8** [comment]
Hi @Armychais902 
This folder was accidentally removed by gitignore. Added it back in now in e0f0aee.
